"""Convert the supplied transparent logo to the minimal LCD splash.

Usage: python tools/generate_boot_assets.py --preview /path/to/preview.png
Requires Pillow; generated firmware has no font/Pillow dependency.
"""
import argparse
import hashlib
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]


def xbm(image):
    bits = []
    for y in range(image.height):
        for x in range(0, image.width, 8):
            byte = 0
            for bit in range(8):
                if x + bit < image.width and image.getpixel((x + bit, y)):
                    byte |= 1 << bit
            bits.append(byte)
    return ",\n  ".join(", ".join(f"0x{v:02x}" for v in bits[i:i + 16]) for i in range(0, len(bits), 16))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", help="Legacy argument; minimal splash needs no font")
    parser.add_argument("--preview")
    args = parser.parse_args()
    source = ROOT / "doc/boot-logo-source.png"
    rgba = Image.open(source).convert("RGBA")
    alpha = rgba.getchannel("A")
    alpha = alpha.crop(alpha.getbbox())
    alpha.thumbnail((50, 32), Image.Resampling.LANCZOS)
    logo = alpha.point(lambda p: 255 if p >= 128 else 0).convert("1")
    result = ["#pragma once", "// Generated by tools/generate_boot_assets.py; LSB-first XBM.",
              f"// Supplied PNG SHA256: {hashlib.sha256(source.read_bytes()).hexdigest()}",
              "#include <Arduino.h>", f"constexpr uint8_t BOOT_LOGO_WIDTH = {logo.width}U;",
              f"constexpr uint8_t BOOT_LOGO_HEIGHT = {logo.height}U;",
              "constexpr uint8_t BOOT_LOGO_TOP = 16U;",
              "static const uint8_t bootLogoBits[] PROGMEM = {\n  " + xbm(logo) + "\n};"]
    (ROOT / "MAYAP_INDUSTRIAL_v4_0_0/boot_assets.h").write_text("\n".join(result) + "\n", encoding="utf-8")
    if args.preview:
        frame = Image.new("1", (128, 64), 1)
        frame.paste(0, ((128 - logo.width) // 2, 16), logo)
        draw = ImageDraw.Draw(frame)
        for x in (60, 64, 68):
            draw.ellipse((x - 1, 56, x + 1, 58), fill=0)
        preview = frame.resize((512, 256), Image.Resampling.NEAREST)
        preview.save(args.preview)


if __name__ == "__main__":
    main()
