"""Convert the supplied transparent logo and Vietnamese labels to LCD XBM.

Usage: python tools/generate_boot_assets.py --font /path/to/arial.ttf
Requires Pillow; generated firmware does not depend on fonts or Pillow.
"""
import argparse
import hashlib
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
LABELS = ["Kiểm tra phần cứng", "Khởi tạo bộ nhớ", "Khởi tạo cảm biến",
          "Khởi tạo điều khiển", "Khởi tạo an toàn", "Kết nối mạng",
          "Kết nối máy chủ", "Hệ thống sẵn sàng"]


def xbm(image):
    bits = []
    for y in range(image.height):
        for x in range(0, image.width, 8):
            byte = 0
            for bit in range(8):
                if x + bit < image.width and image.getpixel((x + bit, y)):
                    byte |= 1 << bit
            bits.append(byte)
    return ",\n  ".join(", ".join(f"0x{v:02x}" for v in bits[i:i + 16]) for i in range(0, len(bits), 16))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", required=True)
    parser.add_argument("--preview")
    args = parser.parse_args()
    source = ROOT / "doc/boot-logo-source.png"
    rgba = Image.open(source).convert("RGBA")
    alpha = rgba.getchannel("A")
    alpha = alpha.crop(alpha.getbbox())
    alpha.thumbnail((70, 45), Image.Resampling.LANCZOS)
    logo = alpha.point(lambda p: 255 if p >= 128 else 0).convert("1")
    result = ["#pragma once", "// Generated by tools/generate_boot_assets.py; LSB-first XBM.",
              f"// Supplied PNG SHA256: {hashlib.sha256(source.read_bytes()).hexdigest()}",
              "#include <Arduino.h>", f"constexpr uint8_t BOOT_LOGO_WIDTH = {logo.width}U;",
              f"constexpr uint8_t BOOT_LOGO_HEIGHT = {logo.height}U;",
              "static const uint8_t bootLogoBits[] PROGMEM = {\n  " + xbm(logo) + "\n};"]
    frames = []
    for index, label in enumerate(LABELS):
        size = 12
        while True:
            font = ImageFont.truetype(args.font, size)
            bbox = font.getbbox(label)
            if bbox[2] - bbox[0] <= 124 and bbox[3] - bbox[1] <= 14:
                break
            size -= 1
            if size < 8:
                raise ValueError("Font cannot fit Vietnamese label in one line")
        bitmap = Image.new("L", (128, 14), 0)
        draw = ImageDraw.Draw(bitmap)
        draw.text(((128 - (bbox[2] - bbox[0])) // 2 - bbox[0], -bbox[1]), label, font=font, fill=255)
        bitmap = bitmap.point(lambda p: 255 if p >= 80 else 0).convert("1")
        result.append(f"// {label}\nstatic const uint8_t bootStatus{index}[] PROGMEM = {{\n  " + xbm(bitmap) + "\n};")
        frame = Image.new("1", (128, 64), 1)
        frame.paste(0, ((128 - logo.width) // 2, 3), logo)
        frame.paste(0, (0, 49), bitmap)
        frames.append(frame)
    result.append("static const uint8_t *const bootStatusBits[] = {" + ", ".join(f"bootStatus{i}" for i in range(8)) + "};")
    (ROOT / "MAYAP_INDUSTRIAL_v4_0_0/boot_assets.h").write_text("\n".join(result) + "\n", encoding="utf-8")
    if args.preview:
        preview = Image.new("RGB", (512, 128 * 4), "white")
        for index, frame in enumerate(frames):
            preview.paste(frame.resize((256, 128), Image.Resampling.NEAREST), ((index % 2) * 256, (index // 2) * 128))
        preview.save(args.preview)


if __name__ == "__main__":
    main()
